version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: pizza-nginx
    ports:
      - "8080:80"
    volumes:
      - ./PIZZA:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    container_name: pizza-php
    volumes:
      - ./PIZZA:/var/www/html
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pizza_db       # must match your actual database with tables
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: pizza-postgres
    restart: always
    environment:
      POSTGRES_DB: pizza_db   # <-- create pizza_db instead of pizza_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data   # persistent data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pizza-pgadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pizza.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres-data:
